# Generated by Django 4.2.5 on 2023-09-09 07:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
