# Generated by Django 4.2.5 on 2023-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
